[package]
name = "better-hand"
version = "0.1.0"
authors = ["Adithya Chari <adithya.chari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_poker = "1.0.0"
rayon = "1.5.0"
clap = "2.33.3"